name       : zim
version    : 0.74.1
release    : 24
source     :
    - https://github.com/zim-desktop-wiki/zim-desktop-wiki/archive/refs/tags/0.74.1.tar.gz : c2775df72d2877cfefb5357d807e853a0c361abf12e7b63222c30b972f43c954
license    : GPL-2.0-or-later
component  : office.notes
summary    : A WYSIWYG text editor and desktop wiki
description: |
    Zim is a graphical text editor used to maintain a collection of wiki pages. Each page can contain links to other pages, simple formatting and images. Pages are stored in a folder structure, like in an outliner, and can have attachments. Creating a new page is as easy as linking to a nonexistent page. All data is stored in plain text files with wiki formatting. Various plugins provide additional functionality, like a task list manager, an equation editor, a tray icon, and support for version control.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(pygobject-3.0)
rundeps    :
    - gnuplot
    - graphviz
    - python-gobject
    - pyxdg
    - scrot
    - xdg-utils
build      : |
    %python3_setup
install    : |
    %python3_install --skip-build
    sed -i 's/Utility;TextEditor;GTK;/Office;/g' $installdir/usr/share/applications/zim.desktop
