name       : zim
version    : '0.69'
release    : 10
source     :
    - https://github.com/jaap-karssenberg/zim-desktop-wiki/archive/0.69.tar.gz : 48205c533f1df4d8b143d5bc5adc09a6cd979c53a5d6b504922d8ac28b57e532
license    : GPL-2.0-or-later
component  : office.notes
summary    : A WYSIWYG text editor and desktop wiki
description: |
    Zim is a graphical text editor used to maintain a collection of wiki pages. Each page can contain links to other pages, simple formatting and images. Pages are stored in a folder structure, like in an outliner, and can have attachments. Creating a new page is as easy as linking to a nonexistent page. All data is stored in plain text files with wiki formatting. Various plugins provide additional functionality, like a task list manager, an equation editor, a tray icon, and support for version control.
builddeps  :
    - pkgconfig(pygobject-2.0)
    - python-setuptools
rundeps    :
    - gnuplot
    - graphviz
    - python-gobject2
    - python-gtk2
    - python-setuptools
    - pyxdg
    - scrot
    - xdg-utils
build      : |
    %python_setup
install    : |
    %python_install --skip-xdg-cmd --skip-build
    sed -i 's/Utility;TextEditor;GTK;/Office;/g' $installdir/usr/share/applications/zim.desktop
